# task config
task: fixed_pairing

# simulation config
sim_freq: 60
agent_interaction_steps: 12 # step 0.2s

# termination config
max_steps: 4000
altitude_limit: 2500
acceleration_limit_x: 10.0
acceleration_limit_y: 10.0
acceleration_limit_z: 10.0

# aircraft config
aircraft_configs: {
  A0100: {
    color: Red,
    model: f16,
    init_state: {
      ic_long_gc_deg: 120.0,
      ic_lat_geod_deg: 60.0,
      ic_h_sl_ft: 20000,
      ic_psi_true_deg: 0.0,
      ic_u_fps: 800.0,
    },
  },
  A0200: {
    color: Red,
    model: f16,
    init_state: {
      ic_long_gc_deg: 120.0,
      ic_lat_geod_deg: 59.85,
      ic_h_sl_ft: 20000,
      ic_psi_true_deg: 0.0,
      ic_u_fps: 800.0,
    },
  },
  A0300: {
    color: Red,
    model: f16,
    init_state: {
      ic_long_gc_deg: 119.85,
      ic_lat_geod_deg: 60.0,
      ic_h_sl_ft: 20000,
      ic_psi_true_deg: 0.0,
      ic_u_fps: 800.0,
    },
  },
  A0400: {
    color: Red,
    model: f16,
    init_state: {
      ic_long_gc_deg: 119.85,
      ic_lat_geod_deg: 59.85,
      ic_h_sl_ft: 20000,
      ic_psi_true_deg: 0.0,
      ic_u_fps: 800.0,
    },
  },
  B0100: {
    color: Blue,
    model: f16,
    init_state: {
      ic_h_sl_ft: 20000,
      ic_lat_geod_deg: 60.45,
      ic_long_gc_deg: 120.0,
      ic_psi_true_deg: 180.0,
      ic_u_fps: 800.0,
    },
  },
  B0200: {
    color: Blue,
    model: f16,
    init_state: {
      ic_h_sl_ft: 20000,
      ic_lat_geod_deg: 60.10,
      ic_long_gc_deg: 120.0,
      ic_psi_true_deg: 180.0,
      ic_u_fps: 800.0,
    },
  },
    B0300: {
    color: Blue,
    model: f16,
    init_state: {
      ic_h_sl_ft: 20000,
      ic_lat_geod_deg: 60.15,
      ic_long_gc_deg: 119.95,
      ic_psi_true_deg: 180.0,
      ic_u_fps: 800.0,
    },
  },
  B0400: {
    color: Blue,
    model: f16,
    init_state: {
      ic_h_sl_ft: 20000,
      ic_lat_geod_deg: 60.30,
      ic_long_gc_deg: 119.95,
      ic_psi_true_deg: 180.0,
      ic_u_fps: 800.0,
    },
  }
}
# (lontitude, latitude, altitude)
battle_field_center: [120.0, 60.0, 0.0] 